// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: javalex.l

package ch9;

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class Yylex {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\6\1\7\2\0\1\10\1\11\1\0\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\12\22\1\23"+
    "\1\24\1\25\1\26\1\27\2\0\4\30\1\31\25\30"+
    "\1\32\1\33\1\34\1\0\1\30\1\0\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\45\1\30"+
    "\1\46\1\47\1\30\1\50\1\51\1\52\1\30\1\53"+
    "\1\54\1\55\1\56\1\57\1\60\3\30\1\61\1\62"+
    "\1\63\7\0\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\1\1\5\1\1"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\15\24\1\27\1\1\1\30\1\31\1\0\1\32"+
    "\1\0\1\33\1\34\1\35\1\36\3\0\1\37\1\40"+
    "\1\41\7\24\1\42\11\24\1\43\1\32\1\0\1\36"+
    "\1\0\1\44\1\0\6\24\1\45\1\46\1\47\14\24"+
    "\1\50\1\51\4\24\1\52\1\53\2\24\1\54\1\55"+
    "\5\24\1\56\1\24\1\57\1\60\1\61\1\62\1\63"+
    "\1\64";

  private static int [] zzUnpackAction() {
    int [] result = new int[125];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\64\0\234\0\320\0\64\0\u0104"+
    "\0\64\0\64\0\64\0\u0138\0\64\0\u016c\0\u01a0\0\u01d4"+
    "\0\u0208\0\64\0\64\0\u023c\0\u0270\0\u02a4\0\u02d8\0\64"+
    "\0\64\0\u030c\0\u0340\0\u0374\0\u03a8\0\u03dc\0\u0410\0\u0444"+
    "\0\u0478\0\u04ac\0\u04e0\0\u0514\0\u0548\0\u057c\0\64\0\u05b0"+
    "\0\64\0\64\0\320\0\64\0\u05e4\0\64\0\64\0\64"+
    "\0\u01a0\0\u0618\0\u064c\0\u0680\0\64\0\64\0\64\0\u06b4"+
    "\0\u06e8\0\u071c\0\u0750\0\u0784\0\u07b8\0\u07ec\0\u02d8\0\u0820"+
    "\0\u0854\0\u0888\0\u08bc\0\u08f0\0\u0924\0\u0958\0\u098c\0\u09c0"+
    "\0\64\0\320\0\u09f4\0\u09f4\0\u0a28\0\64\0\u0a5c\0\u0a90"+
    "\0\u0ac4\0\u0af8\0\u0b2c\0\u0b60\0\u0b94\0\u02d8\0\u02d8\0\u02d8"+
    "\0\u0bc8\0\u0bfc\0\u0c30\0\u0c64\0\u0c98\0\u0ccc\0\u0d00\0\u0d34"+
    "\0\u0d68\0\u0d9c\0\u0dd0\0\u0e04\0\u02d8\0\u02d8\0\u0e38\0\u0e6c"+
    "\0\u0ea0\0\u0ed4\0\u02d8\0\u02d8\0\u0f08\0\u0f3c\0\u02d8\0\u02d8"+
    "\0\u0f70\0\u0fa4\0\u0fd8\0\u100c\0\u1040\0\u02d8\0\u1074\0\u02d8"+
    "\0\u02d8\0\u02d8\0\u02d8\0\u02d8\0\u02d8";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[125];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\0\2\3\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\2\27"+
    "\1\30\1\2\1\31\1\27\1\32\1\33\1\34\1\35"+
    "\1\36\2\27\1\37\2\27\1\40\1\27\1\41\1\42"+
    "\1\43\1\44\1\27\1\45\1\46\1\47\1\50\1\51"+
    "\65\0\1\3\2\0\2\3\104\0\1\52\35\0\7\53"+
    "\1\54\23\53\1\55\30\53\11\0\1\56\100\0\1\57"+
    "\63\0\1\60\57\0\1\61\6\0\1\62\7\0\1\62"+
    "\36\0\1\63\4\0\1\64\62\0\1\61\1\0\1\21"+
    "\6\0\1\62\7\0\1\62\50\0\1\65\63\0\1\66"+
    "\63\0\1\67\57\0\1\27\5\0\2\27\3\0\24\27"+
    "\25\0\1\27\5\0\2\27\3\0\14\27\1\70\1\27"+
    "\1\71\5\27\25\0\1\27\5\0\2\27\3\0\12\27"+
    "\1\72\11\27\25\0\1\27\5\0\2\27\3\0\14\27"+
    "\1\73\7\27\25\0\1\27\5\0\2\27\3\0\12\27"+
    "\1\74\11\27\25\0\1\27\5\0\2\27\3\0\1\75"+
    "\13\27\1\76\7\27\25\0\1\27\5\0\2\27\3\0"+
    "\5\27\1\77\5\27\1\100\10\27\25\0\1\27\5\0"+
    "\2\27\3\0\4\27\1\101\14\27\1\102\2\27\25\0"+
    "\1\27\5\0\2\27\3\0\21\27\1\103\2\27\25\0"+
    "\1\27\5\0\2\27\3\0\4\27\1\104\17\27\25\0"+
    "\1\27\5\0\2\27\3\0\20\27\1\105\3\27\25\0"+
    "\1\27\5\0\2\27\3\0\16\27\1\106\5\27\25\0"+
    "\1\27\5\0\2\27\3\0\14\27\1\107\7\27\25\0"+
    "\1\27\5\0\2\27\3\0\7\27\1\110\14\27\65\0"+
    "\1\111\1\0\7\53\1\112\23\53\1\55\30\53\15\0"+
    "\1\113\1\0\1\113\2\0\1\114\41\0\14\63\1\115"+
    "\47\63\2\64\1\116\2\0\1\117\56\64\22\0\1\27"+
    "\5\0\2\27\3\0\14\27\1\120\7\27\25\0\1\27"+
    "\5\0\2\27\3\0\4\27\1\121\17\27\25\0\1\27"+
    "\5\0\2\27\3\0\1\122\23\27\25\0\1\27\5\0"+
    "\2\27\3\0\21\27\1\123\2\27\25\0\1\27\5\0"+
    "\2\27\3\0\17\27\1\124\4\27\25\0\1\27\5\0"+
    "\2\27\3\0\12\27\1\125\11\27\25\0\1\27\5\0"+
    "\2\27\3\0\16\27\1\126\5\27\25\0\1\27\5\0"+
    "\2\27\3\0\20\27\1\127\3\27\25\0\1\27\5\0"+
    "\2\27\3\0\23\27\1\130\25\0\1\27\5\0\2\27"+
    "\3\0\12\27\1\131\11\27\25\0\1\27\5\0\2\27"+
    "\3\0\1\27\1\132\22\27\25\0\1\27\5\0\2\27"+
    "\3\0\20\27\1\133\3\27\25\0\1\27\5\0\2\27"+
    "\3\0\1\134\15\27\1\135\5\27\25\0\1\27\5\0"+
    "\2\27\3\0\21\27\1\136\2\27\25\0\1\27\5\0"+
    "\2\27\3\0\10\27\1\137\13\27\25\0\1\27\5\0"+
    "\2\27\3\0\10\27\1\140\13\27\25\0\1\114\41\0"+
    "\14\63\1\115\4\63\1\116\42\63\2\0\1\116\103\0"+
    "\1\27\5\0\2\27\3\0\12\27\1\141\11\27\25\0"+
    "\1\27\5\0\2\27\3\0\1\142\23\27\25\0\1\27"+
    "\5\0\2\27\3\0\17\27\1\143\4\27\25\0\1\27"+
    "\5\0\2\27\3\0\1\27\1\144\22\27\25\0\1\27"+
    "\5\0\2\27\3\0\4\27\1\145\17\27\25\0\1\27"+
    "\5\0\2\27\3\0\17\27\1\136\4\27\25\0\1\27"+
    "\5\0\2\27\3\0\12\27\1\146\11\27\25\0\1\27"+
    "\5\0\2\27\3\0\12\27\1\147\11\27\25\0\1\27"+
    "\5\0\2\27\3\0\21\27\1\150\2\27\25\0\1\27"+
    "\5\0\2\27\3\0\20\27\1\151\3\27\25\0\1\27"+
    "\5\0\2\27\3\0\10\27\1\152\13\27\25\0\1\27"+
    "\5\0\2\27\3\0\4\27\1\153\17\27\25\0\1\27"+
    "\5\0\2\27\3\0\3\27\1\154\20\27\25\0\1\27"+
    "\5\0\2\27\3\0\12\27\1\155\11\27\25\0\1\27"+
    "\5\0\2\27\3\0\4\27\1\156\17\27\25\0\1\27"+
    "\5\0\2\27\3\0\11\27\1\157\12\27\25\0\1\27"+
    "\5\0\2\27\3\0\17\27\1\160\4\27\25\0\1\27"+
    "\5\0\2\27\3\0\12\27\1\161\11\27\25\0\1\27"+
    "\5\0\2\27\3\0\10\27\1\162\13\27\25\0\1\27"+
    "\5\0\2\27\3\0\16\27\1\163\5\27\25\0\1\27"+
    "\5\0\2\27\3\0\10\27\1\164\13\27\25\0\1\27"+
    "\5\0\2\27\3\0\13\27\1\165\10\27\25\0\1\27"+
    "\5\0\2\27\3\0\4\27\1\166\17\27\25\0\1\27"+
    "\5\0\2\27\3\0\1\167\23\27\25\0\1\27\5\0"+
    "\2\27\3\0\4\27\1\170\17\27\25\0\1\27\5\0"+
    "\2\27\3\0\2\27\1\171\21\27\25\0\1\27\5\0"+
    "\2\27\3\0\13\27\1\172\10\27\25\0\1\27\5\0"+
    "\2\27\3\0\2\27\1\173\21\27\25\0\1\27\5\0"+
    "\2\27\3\0\6\27\1\174\15\27\25\0\1\27\5\0"+
    "\2\27\3\0\13\27\1\175\10\27\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4264];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\2\1\1\11\1\1\3\11"+
    "\1\1\1\11\4\1\2\11\4\1\2\11\15\1\1\11"+
    "\1\1\2\11\1\0\1\11\1\0\3\11\1\1\3\0"+
    "\3\11\21\1\1\11\1\1\1\0\1\1\1\0\1\11"+
    "\1\0\56\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[125];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { j0.lexErr("unrecognized character");
            }
            // fall through
          case 53: break;
          case 2:
            { j0.whitespace();
            }
            // fall through
          case 54: break;
          case 3:
            { j0.newline();
            }
            // fall through
          case 55: break;
          case 4:
            { return j0.scan(j0.ord("!"));
            }
            // fall through
          case 56: break;
          case 5:
            { return j0.scan(j0.ord("%"));
            }
            // fall through
          case 57: break;
          case 6:
            { return j0.scan(j0.ord("("));
            }
            // fall through
          case 58: break;
          case 7:
            { return j0.scan(j0.ord(")"));
            }
            // fall through
          case 59: break;
          case 8:
            { return j0.scan(j0.ord("*"));
            }
            // fall through
          case 60: break;
          case 9:
            { return j0.scan(j0.ord("+"));
            }
            // fall through
          case 61: break;
          case 10:
            { return j0.scan(j0.ord(","));
            }
            // fall through
          case 62: break;
          case 11:
            { return j0.scan(j0.ord("-"));
            }
            // fall through
          case 63: break;
          case 12:
            { return j0.scan(j0.ord("."));
            }
            // fall through
          case 64: break;
          case 13:
            { return j0.scan(j0.ord("/"));
            }
            // fall through
          case 65: break;
          case 14:
            { return j0.scan(parser.INTLIT);
            }
            // fall through
          case 66: break;
          case 15:
            { return j0.scan(j0.ord(":"));
            }
            // fall through
          case 67: break;
          case 16:
            { return j0.scan(j0.ord(";"));
            }
            // fall through
          case 68: break;
          case 17:
            { return j0.scan(j0.ord("<"));
            }
            // fall through
          case 69: break;
          case 18:
            { return j0.scan(j0.ord("="));
            }
            // fall through
          case 70: break;
          case 19:
            { return j0.scan(j0.ord(">"));
            }
            // fall through
          case 71: break;
          case 20:
            { return j0.scan(parser.IDENTIFIER);
            }
            // fall through
          case 72: break;
          case 21:
            { return j0.scan(j0.ord("["));
            }
            // fall through
          case 73: break;
          case 22:
            { return j0.scan(j0.ord("]"));
            }
            // fall through
          case 74: break;
          case 23:
            { return j0.scan(j0.ord("{"));
            }
            // fall through
          case 75: break;
          case 24:
            { return j0.scan(j0.ord("}"));
            }
            // fall through
          case 76: break;
          case 25:
            { return j0.scan(parser.NOTEQUALTO);
            }
            // fall through
          case 77: break;
          case 26:
            { return j0.scan(parser.STRINGLIT);
            }
            // fall through
          case 78: break;
          case 27:
            { return j0.scan(parser.LOGICALAND);
            }
            // fall through
          case 79: break;
          case 28:
            { return j0.scan(parser.INCREMENT);
            }
            // fall through
          case 80: break;
          case 29:
            { return j0.scan(parser.DECREMENT);
            }
            // fall through
          case 81: break;
          case 30:
            { return j0.scan(parser.DOUBLELIT);
            }
            // fall through
          case 82: break;
          case 31:
            { return j0.scan(parser.LESSTHANOREQUAL);
            }
            // fall through
          case 83: break;
          case 32:
            { return j0.scan(parser.ISEQUALTO);
            }
            // fall through
          case 84: break;
          case 33:
            { return j0.scan(parser.GREATERTHANOREQUAL);
            }
            // fall through
          case 85: break;
          case 34:
            { return j0.scan(parser.IF);
            }
            // fall through
          case 86: break;
          case 35:
            { return j0.scan(parser.LOGICALOR);
            }
            // fall through
          case 87: break;
          case 36:
            { j0.comment();
            }
            // fall through
          case 88: break;
          case 37:
            { return j0.scan(parser.FOR);
            }
            // fall through
          case 89: break;
          case 38:
            { return j0.scan(parser.INT);
            }
            // fall through
          case 90: break;
          case 39:
            { return j0.scan(parser.NEW);
            }
            // fall through
          case 91: break;
          case 40:
            { return j0.scan(parser.ELSE);
            }
            // fall through
          case 92: break;
          case 41:
            { return j0.scan(parser.NULLVAL);
            }
            // fall through
          case 93: break;
          case 42:
            { return j0.scan(parser.BOOLLIT);
            }
            // fall through
          case 94: break;
          case 43:
            { return j0.scan(parser.VOID);
            }
            // fall through
          case 95: break;
          case 44:
            { return j0.scan(parser.BREAK);
            }
            // fall through
          case 96: break;
          case 45:
            { return j0.scan(parser.CLASS);
            }
            // fall through
          case 97: break;
          case 46:
            { return j0.scan(parser.WHILE);
            }
            // fall through
          case 98: break;
          case 47:
            { return j0.scan(parser.DOUBLE);
            }
            // fall through
          case 99: break;
          case 48:
            { return j0.scan(parser.PUBLIC);
            }
            // fall through
          case 100: break;
          case 49:
            { return j0.scan(parser.RETURN);
            }
            // fall through
          case 101: break;
          case 50:
            { return j0.scan(parser.STATIC);
            }
            // fall through
          case 102: break;
          case 51:
            { return j0.scan(parser.STRING);
            }
            // fall through
          case 103: break;
          case 52:
            { return j0.scan(parser.BOOLEAN);
            }
            // fall through
          case 104: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
